version: '3.9'

services:
  # Database PostgreSQL
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: whatsapp_bot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - whatsapp-net

  # Backend Spring Boot service
  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - whatsapp-net

  # Opzionale: expose backend via Ngrok
  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      - backend
    command: "tcp 8080"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    networks:
      - whatsapp-net
    # Visualizza i log nel terminale
    tty: true

volumes:
  postgres-data:

networks:
  whatsapp-net:
    external: false
