version: '3.9'

services:
  # Database PostgreSQL
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: whatsapp_bot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - whatsapp-net

  # pgAdmin per gestione database
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - whatsapp-net

  # Backend Spring Boot service
  backend:
    build:
      context: ./backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - whatsapp-net

  # Opzionale: expose backend via Ngrok
  # ngrok:
  #   image: ngrok/ngrok:latest
  #   depends_on:
  #     - backend
  #   command: "tcp 8080"
  #   environment:
  #     NGROK_AUTHTOKEN: 2P1Xy7kC1sLhJHJ6nN3RM6BqPrq_xxxxxxxx
  #   networks:
  #     - whatsapp-net
  #   tty: true

volumes:
  postgres-data:

networks:
  whatsapp-net:
    external: false
