server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsbot
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  pattern:
    console: '{"time":"%d{ISO8601}","level":"%p","logger":"%c{1}","message":"%m"}%n'
  file:
    name: logs/whatsbot.log

whatsapp:
  phone-number-id: YOUR_PHONE_NUMBER_ID
  access-token: YOUR_ACCESS_TOKEN
