server:
  port: 8080

logging:
  level:
    root: INFO
  pattern:
    console: '{"time":"%d{ISO8601}","level":"%p","logger":"%c{1}","message":"%m"}%n'
  file:
    name: whatsbot.log
    path: logs

spring:
  datasource:
    url: jdbc:h2:mem:whatsbot;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: false


whatsapp:
  base-url: ${WHATSAPP_BASE_URL:https://graph.facebook.com/v17.0}
  phone-number-id: ${WHATSAPP_PHONE_NUMBER_ID}
  access-token: ${WHATSAPP_ACCESS_TOKEN}
  app-secret: ${WHATSAPP_APP_SECRET}

webhook:
  token-ngrok: ${NGROK_AUTHTOKEN}

cors:
  enabled: true
  allowed-origins:
    - "http://localhost:3000"

info:
  open-hours:
    monday-friday: "9-18"
    saturday: "10-14"
