server:
  port: 8080

logging:
  level:
    root: INFO
  pattern:
    console: '{"time":"%d{ISO8601}","level":"%p","logger":"%c{1}","message":"%m"}%n'
  file:
    name: logs/whatsbot.log

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsbot
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

whatsapp:
  base-url: https://graph.facebook.com/v17.0
  phone-number-id: +14155238886

webhook:
  token: 2yoLDChUDPYrOz1BcUrRaPWv1r5_52dYmvKqSTaao6nkcnaGs
  twilio-auth-token: ShZjoEdha6VOawwcseZUqGoV9sYad4c8

cors:
  enabled: true
  allowed-origins:
    - "http://localhost:3000"
