spring:
  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    root: INFO
  pattern:
    console: '{"time":"%d{ISO8601}","level":"%p","logger":"%c{1}","message":"%m"}%n'
  file:
    name: logs/whatsbot.log
