server:
  port: 8080

logging:
  level:
    root: INFO
  pattern:
    console: '{"time":"%d{ISO8601}","level":"%p","logger":"%c{1}","message":"%m"}%n'
  file:
    name: logs/whatsbot.log

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/whatsapp_bot
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


whatsapp:
  base-url: https://graph.facebook.com/v17.0
  phone-number-id: +14155238886
  app-secret: change-me

webhook:
  token-ngrok: 2yoLDChUDPYrOz1BcUrRaPWv1r5_52dYmvKqSTaao6nkcnaGs


cors:
  enabled: true
  allowed-origins:
    - "http://localhost:3000"

info:
  open-hours:
    monday-friday: "9-18"
    saturday: "10-14"
