server:
  port: 8080

logging:
  level:
    root: INFO
  pattern:
    console: '{"time":"%d{ISO8601}","level":"%p","logger":"%c{1}","message":"%m"}%n'
  file:
    name: logs/whatsbot.log

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsbot_dev
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

whatsapp:
  base-url: ${WHATSAPP_BASE_URL:https://graph.facebook.com/v17.0}
  phone-number-id: ${WHATSAPP_PHONE_NUMBER_ID}
#  access-token: ${WHATSAPP_ACCESS_TOKEN}
#  app-secret: ${WHATSAPP_APP_SECRET}
  access-token: ajfofabfowegwrn0230922vbuf2cn2c2ifwengnrugn949g93g3
  app-secret: afna33432jsovw45v0329552fsefagagregwsfegsfaf

webhook:
  token-ngrok: ${NGROK_AUTHTOKEN}

cors:
  enabled: true
  allowed-origins:
    - "http://localhost:3000"

info:
  open-hours:
    monday-friday: "9-18"
    saturday: "10-14"
